---
# tasks file for ansible-role-ynab-stuff

- name: clone bank2ynab
  git:
    repo: "{{ ynab_bank2ynab_git_repo }}"
    dest: "{{ ynab_bank2ynab_git_dest }}"
    version: "{{ ynab_bank2ynab_git_version }}"
    force: "{{ ynab_bank2ynab_git_repo_force }}"
    update: "{{ ynab_bank2ynab_git_repo_update }}"

- name: setting permissions
  file:
    path: "{{ ynab_bank2ynab_git_dest }}"
    owner: "{{ ynab_user }}"
    group: "{{ ynab_group }}"
    recurse: yes

- name: configure bank2ynab with additional banks
  blockinfile:
    dest: "{{ ynab_bank2ynab_git_dest }}/bank2ynab.conf"
    block: "{{ lookup('template', 'bank2ynab.conf.j2') }}"
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"

- name: configure "Source Path"
  blockinfile:
    dest: "{{ ynab_bank2ynab_git_dest }}/user_configuration.conf"
    block: |
      [DEFAULT]
      Source Path = {{ ynab_bank2ynab_git_source_path_csv }}
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    create: yes

- name: ynab_bank2ynab_git_source_path_csv must exist
  file:
    path: "{{ ynab_bank2ynab_git_source_path_csv }}"
    state: directory
    owner: "{{ ynab_user }}"
    group: "{{ ynab_group }}"

- name: Configure cron
  cron:
    name: run bank2ynab.py
    user: "{{ ynab_user }}"
    job: "cd {{ ynab_bank2ynab_git_dest }} && python3 {{ ynab_bank2ynab_git_dest }}/bank2ynab.py"
    cron_file: ynab_stuff

- name: Configure cron 2
  cron:
    name: run bank2ynab.py 2
    user: "{{ ynab_user }}"
    job: "(sleep 30 ; cd {{ ynab_bank2ynab_git_dest }} && python3 {{ ynab_bank2ynab_git_dest }}/bank2ynab.py)"
    cron_file: ynab_stuff
